#!/usr/bin/env python3
"""End-to-end tests for frontier-brain installer.

Uses a temp directory as CLAUDE_HOME to avoid touching real ~/.claude/.
Each test scenario gets a fresh temp dir.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
import tempfile
import textwrap
from pathlib import Path
from unittest import mock

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "installer"))

import installer.main as installer

PASS = 0
FAIL = 0
RESULTS: list[tuple[str, bool, str]] = []


def report(name: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        PASS += 1
    else:
        FAIL += 1
    RESULTS.append((name, ok, detail))
    status = "PASS" if ok else "FAIL"
    msg = f"  [{status}] {name}"
    if detail and not ok:
        msg += f" — {detail}"
    print(msg)


def patch_home(tmp: Path):
    """Return a dict of patches that redirect installer to use tmp as CLAUDE_HOME."""
    return {
        "installer.main.CLAUDE_HOME": tmp,
        "installer.main.MANIFEST_PATH": tmp / "frontier-brain" / ".manifest",
        "installer.main.SETTINGS_PATH": tmp / "settings.json",
        "installer.main.SETTINGS_BACKUP_PATH": tmp / "settings.json.bak-frontier-brain",
    }


def apply_patches(patches: dict):
    """Apply mock.patch for each key-value pair. Returns patcher list."""
    patchers = []
    for target, value in patches.items():
        p = mock.patch(target, value)
        p.start()
        patchers.append(p)
    return patchers


def stop_patches(patchers):
    for p in patchers:
        p.stop()


def count_managed_files_in(d: Path) -> int:
    """Count files, excluding __pycache__ (generated by Python runtime)."""
    if not d.exists():
        return 0
    return sum(1 for f in d.rglob("*") if f.is_file() and "__pycache__" not in f.parts)


# ─── Scenario 1: Fresh install on empty home ────────────────────────────

def test_fresh_install():
    print("\n── Scenario 1: Fresh install on empty CLAUDE_HOME")
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        patches = patch_home(tmp)
        patchers = apply_patches(patches)
        try:
            installer.main(["install"])

            manifest_path = tmp / "frontier-brain" / ".manifest"
            report("manifest created", manifest_path.exists())

            manifest = json.loads(manifest_path.read_text())
            report("manifest has commit", manifest.get("commit") is not None and manifest["commit"] != "None")
            report("manifest has files", len(manifest.get("files", [])) > 0)

            expected_files = [
                tmp / "frontier-brain" / "bin" / "decision-engine.py",
                tmp / "frontier-brain" / "bin" / "visualize.py",
                tmp / "frontier-brain" / "bin" / "static" / "d3.v7.min.js",
                tmp / "frontier-brain" / "bin" / "static" / "index.html",
                tmp / "frontier-brain" / "lib" / "graphdb.py",
                tmp / "frontier-brain" / "lib" / "router.py",
                tmp / "frontier-brain" / "lib" / "frontmatter.py",
                tmp / "hooks" / "frontier-brain" / "decision-detect.py",
                tmp / "skills" / "decision-recall" / "SKILL.md",
                tmp / "skills" / "decision-record" / "SKILL.md",
                tmp / "skills" / "decision-harvest" / "SKILL.md",
                tmp / "skills" / "open-brain" / "SKILL.md",
            ]
            all_exist = all(f.exists() for f in expected_files)
            missing = [str(f.relative_to(tmp)) for f in expected_files if not f.exists()]
            report("all files installed", all_exist, f"missing: {missing}" if missing else "")

            settings_path = tmp / "settings.json"
            report("settings.json created", settings_path.exists())
            if settings_path.exists():
                settings = json.loads(settings_path.read_text())
                hooks = settings.get("hooks", {}).get("UserPromptSubmit", [])
                has_hook = any(
                    "decision-detect" in h.get("command", "")
                    for group in hooks
                    for h in group.get("hooks", [])
                )
                report("hook registered in settings", has_hook)
                hook_uses_py = any(
                    "decision-detect.py" in h.get("command", "")
                    for group in hooks
                    for h in group.get("hooks", [])
                )
                report("hook uses .py (not .js)", hook_uses_py)

            # No backup on fresh install — settings.json didn't exist before merge_hook created it
            backup_path = tmp / "settings.json.bak-frontier-brain"
            report("no backup on fresh install (correct)", not backup_path.exists())

        finally:
            stop_patches(patchers)


# ─── Scenario 2: Upgrade from legacy (no manifest, .js hook exists) ──────

def test_upgrade_from_legacy():
    print("\n── Scenario 2: Upgrade from legacy (no manifest, .js hook)")
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)

        # Pre-seed a legacy settings.json with .js hook
        legacy_settings = {
            "hooks": {
                "UserPromptSubmit": [
                    {
                        "matcher": "",
                        "hooks": [
                            {
                                "type": "command",
                                "command": 'node "/old/path/decision-detect.js"',
                                "timeout": 5,
                            }
                        ],
                    }
                ]
            }
        }
        settings_path = tmp / "settings.json"
        settings_path.write_text(json.dumps(legacy_settings, indent=2))

        patches = patch_home(tmp)
        patchers = apply_patches(patches)
        try:
            installer.main(["install"])

            manifest_path = tmp / "frontier-brain" / ".manifest"
            report("manifest created (from legacy)", manifest_path.exists())

            settings = json.loads(settings_path.read_text())
            hooks = settings.get("hooks", {}).get("UserPromptSubmit", [])
            report("exactly one hook group", len(hooks) == 1, f"got {len(hooks)}")

            has_js = any(
                ".js" in h.get("command", "")
                for group in hooks
                for h in group.get("hooks", [])
            )
            report("old .js hook removed", not has_js)

            has_py = any(
                "decision-detect.py" in h.get("command", "")
                for group in hooks
                for h in group.get("hooks", [])
            )
            report("new .py hook registered", has_py)

        finally:
            stop_patches(patchers)


# ─── Scenario 3: Upgrade from v2 (manifest exists, different commit) ─────

def test_upgrade_v2():
    print("\n── Scenario 3: Upgrade (manifest exists, different commit)")
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        patches = patch_home(tmp)
        patchers = apply_patches(patches)
        try:
            # First install
            installer.main(["install"])
            manifest_path = tmp / "frontier-brain" / ".manifest"
            old_manifest = json.loads(manifest_path.read_text())

            # Fake a different commit in manifest (simulates old version)
            old_manifest["commit"] = "aaaaaaaabbbbbbbbccccccccdddddddd00000000"
            # Add a stale file to test cleanup
            stale_file = tmp / "frontier-brain" / "lib" / "old_module.py"
            stale_file.parent.mkdir(parents=True, exist_ok=True)
            stale_file.write_text("# stale")
            old_manifest["files"].append(str(stale_file))
            manifest_path.write_text(json.dumps(old_manifest, indent=2))

            # Re-install (upgrade)
            installer.main(["install"])

            new_manifest = json.loads(manifest_path.read_text())
            report("commit updated", new_manifest["commit"] != "aaaaaaaabbbbbbbbccccccccdddddddd00000000")
            report("stale file cleaned up", not stale_file.exists())

            # All current files still exist
            missing = [f for f in new_manifest["files"] if not Path(f).exists()]
            report("all current files present after upgrade", len(missing) == 0, f"missing: {missing}")

        finally:
            stop_patches(patchers)


# ─── Scenario 4: Same version — "already up to date" ─────────────────────

def test_same_version():
    print("\n── Scenario 4: Same version → already up to date")
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        patches = patch_home(tmp)
        patchers = apply_patches(patches)
        try:
            installer.main(["install"])
            manifest_path = tmp / "frontier-brain" / ".manifest"
            first_manifest = json.loads(manifest_path.read_text())

            # Capture stdout for second install
            from io import StringIO
            captured = StringIO()
            old_stdout = sys.stdout
            sys.stdout = captured
            try:
                installer.main(["install"])
            finally:
                sys.stdout = old_stdout

            output = captured.getvalue()
            report("prints 'up to date'", "up to date" in output.lower(), f"got: {output.strip()}")
            report("mentions --force", "--force" in output, f"got: {output.strip()}")

            # Manifest unchanged
            second_manifest = json.loads(manifest_path.read_text())
            report("manifest unchanged", first_manifest == second_manifest)

        finally:
            stop_patches(patchers)


# ─── Scenario 5: Same version + --force ──────────────────────────────────

def test_force_reinstall():
    print("\n── Scenario 5: Same version + --force → reinstall")
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        patches = patch_home(tmp)
        patchers = apply_patches(patches)
        try:
            installer.main(["install"])
            manifest_path = tmp / "frontier-brain" / ".manifest"
            first_manifest = json.loads(manifest_path.read_text())
            first_ts = first_manifest["installed_at"]

            # Delete a file to verify --force restores it
            victim = tmp / "frontier-brain" / "lib" / "router.py"
            if victim.exists():
                victim.unlink()

            from io import StringIO
            captured = StringIO()
            old_stdout = sys.stdout
            sys.stdout = captured
            try:
                installer.main(["install", "--force"])
            finally:
                sys.stdout = old_stdout

            output = captured.getvalue()
            report("does NOT say 'up to date'", "up to date" not in output.lower(), f"got: {output.strip()}")
            report("deleted file restored", victim.exists())

            second_manifest = json.loads(manifest_path.read_text())
            report("manifest rewritten on force", second_manifest.get("installed_at") is not None)

        finally:
            stop_patches(patchers)


# ─── Scenario 6: Uninstall ───────────────────────────────────────────────

def test_uninstall():
    print("\n── Scenario 6: Uninstall — files removed, decisions preserved")
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        patches = patch_home(tmp)
        patchers = apply_patches(patches)
        try:
            installer.main(["install"])

            # Create a fake decisions dir with content
            decisions_dir = tmp / "decisions"
            decisions_dir.mkdir(parents=True, exist_ok=True)
            (decisions_dir / "001-test.md").write_text("---\nid: 1\n---\ntest")

            from io import StringIO
            captured = StringIO()
            old_stdout = sys.stdout
            sys.stdout = captured
            try:
                installer.main(["uninstall"])
            finally:
                sys.stdout = old_stdout

            output = captured.getvalue()

            manifest_path = tmp / "frontier-brain" / ".manifest"
            report("manifest deleted", not manifest_path.exists())

            # Managed files gone
            managed_dirs = [
                tmp / "frontier-brain" / "bin",
                tmp / "frontier-brain" / "lib",
                tmp / "hooks" / "frontier-brain",
            ]
            all_gone = all(not d.exists() or count_managed_files_in(d) == 0 for d in managed_dirs)
            remaining = {str(d): count_managed_files_in(d) for d in managed_dirs if d.exists() and count_managed_files_in(d) > 0}
            report("managed files removed", all_gone, f"remaining: {remaining}")

            # Hook removed from settings
            settings_path = tmp / "settings.json"
            if settings_path.exists():
                settings = json.loads(settings_path.read_text())
                hooks = settings.get("hooks", {}).get("UserPromptSubmit", [])
                has_hook = any(
                    "decision-detect" in h.get("command", "")
                    for group in hooks
                    for h in group.get("hooks", [])
                )
                report("hook removed from settings", not has_hook)
            else:
                report("hook removed from settings", True, "settings.json cleaned up entirely")

            # Decisions preserved
            report("decisions/ preserved", (decisions_dir / "001-test.md").exists())
            report("output mentions preservation", "preserved" in output.lower(), f"got: {output.strip()}")

        finally:
            stop_patches(patchers)


# ─── Scenario 7: Uninstall when not installed ────────────────────────────

def test_uninstall_not_installed():
    print("\n── Scenario 7: Uninstall when not installed")
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        patches = patch_home(tmp)
        patchers = apply_patches(patches)
        try:
            from io import StringIO
            captured = StringIO()
            old_stdout = sys.stdout
            sys.stdout = captured
            try:
                installer.main(["uninstall"])
            finally:
                sys.stdout = old_stdout

            output = captured.getvalue()
            report("graceful message", "not installed" in output.lower(), f"got: {output.strip()}")

        finally:
            stop_patches(patchers)


# ─── Scenario 8: Prereq failure ──────────────────────────────────────────

def test_prereq_failure():
    print("\n── Scenario 8: Prereq failure (Python version too low)")
    from types import SimpleNamespace
    fake_version = SimpleNamespace(major=3, minor=10, micro=0, releaselevel="final", serial=0)
    # Make it compare as tuple for the < check
    class FakeVersion(SimpleNamespace):
        def __lt__(self, other):
            return (self.major, self.minor) < other
        def __ge__(self, other):
            return not self.__lt__(other)
    fake = FakeVersion(major=3, minor=10, micro=0, releaselevel="final", serial=0)
    with mock.patch.object(sys, "version_info", fake):
        from io import StringIO
        old_stderr = sys.stderr
        sys.stderr = StringIO()
        try:
            installer.check_prereqs()
            report("check_prereqs exits on old Python", False, "did not exit")
        except SystemExit as e:
            report("check_prereqs exits on old Python", e.code == 1)
        finally:
            sys.stderr = old_stderr


# ─── Scenario 9: Corrupted settings.json ─────────────────────────────────

def test_corrupted_settings():
    print("\n── Scenario 9: Corrupted settings.json — no data loss")
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)

        settings_path = tmp / "settings.json"
        settings_path.write_text("{invalid json oh no")

        patches = patch_home(tmp)
        patchers = apply_patches(patches)
        try:
            # Install should still work (files copy), hook merge should fail gracefully
            from io import StringIO
            captured_err = StringIO()
            captured_out = StringIO()
            old_stderr = sys.stderr
            old_stdout = sys.stdout
            sys.stderr = captured_err
            sys.stdout = captured_out
            try:
                installer.main(["install"])
            finally:
                sys.stderr = old_stderr
                sys.stdout = old_stdout

            err_output = captured_err.getvalue()
            out_output = captured_out.getvalue()

            # Files should still be installed despite settings failure
            manifest_path = tmp / "frontier-brain" / ".manifest"
            report("files installed despite bad settings", manifest_path.exists())

            # Backup should exist
            backup_path = tmp / "settings.json.bak-frontier-brain"
            report("backup of corrupt settings made", backup_path.exists())

            # Original corrupt content preserved in backup
            if backup_path.exists():
                backup_content = backup_path.read_text()
                report("backup has original content", "invalid json" in backup_content)

            report("hook reported as FAILED", "FAILED" in out_output or "could not parse" in err_output)

        finally:
            stop_patches(patchers)


# ─── Run all ──────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("frontier-brain installer — End-to-End Tests")
    print("=" * 60)

    test_fresh_install()
    test_upgrade_from_legacy()
    test_upgrade_v2()
    test_same_version()
    test_force_reinstall()
    test_uninstall()
    test_uninstall_not_installed()
    test_prereq_failure()
    test_corrupted_settings()

    print("\n" + "=" * 60)
    print(f"Results: {PASS} passed, {FAIL} failed, {PASS + FAIL} total")
    if FAIL > 0:
        print("\nFailed:")
        for name, ok, detail in RESULTS:
            if not ok:
                print(f"  FAIL: {name} — {detail}")
    print("=" * 60)
    sys.exit(1 if FAIL > 0 else 0)


if __name__ == "__main__":
    main()
